apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "xxxx"
    azure.workload.identity/tenant-id: "xxxx"
  labels:
    azure.workload.identity/use: "true"
  name: "sa-xxxx"
  namespace: "xxxx"