apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/tenant-id: "12345678-1234-1234-1234-123456789012"
    azure.workload.identity/client-id: "12345678-1234-1234-1234-123456789012"

